[package]
name = "flow-web"
version = "0.1.0"
edition = "2024"

[dependencies]
async-recursion = "1.1.1"
chrono = "0.4.42"
markdown = "1.0.0"
regex = "1.12.2"
sailfish = "0.10.1"
tokio = { version = "1.49.0", features = ["macros", "fs", "io-util", "rt-multi-thread"] }
